[2023-12-01 16:07:03,588] [ERROR] [_internal] 152.74.52.235 - - [01/Dec/2023 16:07:03] code 400, message Bad request version ('ÊÊ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\x9a\x9a\x00\x00\x00')
[2023-12-01 16:07:03,591] [ERROR] [_internal] 152.74.52.235 - - [01/Dec/2023 16:07:03] code 400, message Bad request version ('t\x88ÝJ5')
[2023-12-06 14:54:46,744] [ERROR] [main] Ocurrió un error al agregar la carpeta del ejercicio: integer division or modulo by zero
[2023-12-06 14:54:46,771] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: integer division or modulo by zero
[2023-12-06 14:54:57,388] [ERROR] [main] Ocurrió un error al agregar la carpeta del ejercicio: integer division or modulo by zero
[2023-12-06 14:54:57,395] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: integer division or modulo by zero[2023-12-07 13:42:00,204] [ERROR] [__init__] Error: Path doesn't exist: '/home/ivonne/Documentos/MemoriaTituloIvonne/migrations'.  Please use the 'init' command to create a new scripts folder.
[2023-12-07 13:43:00,134] [ERROR] [__init__] Error: Path doesn't exist: '/home/ivonne/Documentos/MemoriaTituloIvonne/migrations'.  Please use the 'init' command to create a new scripts folder.
[2023-12-07 14:28:05,995] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('1', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-12-11 23:30:26,274] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: ejercicio.nombre
[SQL: INSERT INTO ejercicio (nombre, path_ejercicio, enunciado, id_serie) VALUES (?, ?, ?, ?)]
[parameters: ('Tienda mágica', '', '', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-12-14 14:31:56,583] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('1', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-12-14 17:47:36,821] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('1', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2023-12-21 17:34:03,713] [ERROR] [main] Ocurrió un error al agregar la carpeta del ejercicio: Cannot insert None into a tag.
[2023-12-21 17:34:03,713] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: local variable 'resultadoTest' referenced before assignment
[2023-12-21 17:34:16,941] [ERROR] [main] Ocurrió un error al agregar la carpeta del ejercicio: Cannot insert None into a tag.
[2023-12-21 17:34:16,941] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: local variable 'resultadoTest' referenced before assignment
[2023-12-22 09:37:02,124] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: ejercicio.nombre
[SQL: INSERT INTO ejercicio (nombre, path_ejercicio, enunciado, id_serie) VALUES (?, ?, ?, ?)]
[parameters: ('Tienda mágica p2', '', '', '4')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2024-02-06 12:56:56,219] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'ejerciciosPropuestos/Serie_1'
[2024-02-27 15:18:40,020] [ERROR] [main] Ocurrió un error al eliminar la serie: 'Table' object has no attribute 'query'
[2024-02-27 15:22:56,507] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'ejerciciosPropuestos/Serie_1'
[2024-02-29 11:26:11,997] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_1'
[2024-02-29 12:06:09,174] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_3'
[2024-02-29 14:43:21,485] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_2'
[2024-02-29 14:48:46,200] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_6'
[2024-02-29 14:51:40,090] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_4'
[2024-02-29 14:52:05,362] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_1'
[2024-02-29 14:54:31,634] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_7'
[2024-02-29 14:55:00,254] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_5'
[2024-02-29 14:56:14,596] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'ejerciciosPropuestos/Serie_1'
[2024-02-29 14:57:53,338] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_3'
[2024-02-29 14:58:46,268] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciados/Serie_2'
[2024-02-29 15:00:15,556] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'ejerciciosPropuestos/Serie_2'
[2024-02-29 15:00:24,820] [ERROR] [main] Ocurrió un error al eliminar la serie: [Errno 2] No such file or directory: 'enunciadosPropuestos/Serie_4'
[2024-03-01 19:59:54,320] [ERROR] [main] Ocurrió un error al eliminar el curso: local variable 'estudiantes_grupos' referenced before assignment
[2024-03-01 19:59:56,638] [ERROR] [main] Ocurrió un error al eliminar el curso: local variable 'estudiantes_grupos' referenced before assignment
[2024-03-01 20:02:12,401] [ERROR] [main] Ocurrió un error al eliminar el curso: type object 'Ejercicio_asignado' has no attribute 'delete'
[2024-03-01 20:05:42,111] [ERROR] [main] Ocurrió un error al eliminar el curso: type object 'Ejercicio_asignado' has no attribute 'id_serie'
[2024-03-01 22:23:22,378] [ERROR] [main] Ocurrió un error al eliminar el curso: type object 'Grupo' has no attribute 'delete'
[2024-03-01 22:28:05,946] [ERROR] [main] Ocurrió un error al eliminar el curso: type object 'Estudiante' has no attribute 'delete'
[2024-03-01 22:28:19,878] [ERROR] [main] Ocurrió un error al eliminar el curso: Class 'sqlalchemy.engine.row.Row' is not mapped
[2024-03-01 22:29:16,972] [ERROR] [main] Ocurrió un error al eliminar el curso: Class 'flask_sqlalchemy.model.DefaultMeta' is not mapped; was a class (basedatos.modelos.Ejercicio_asignado) supplied where an instance was required?
[2024-03-01 22:31:45,164] [ERROR] [main] Ocurrió un error al eliminar el curso: Class 'sqlalchemy.engine.row.Row' is not mapped
[2024-03-01 22:36:35,247] [ERROR] [main] Ocurrió un error al eliminar el curso: Class 'sqlalchemy.engine.row.Row' is not mapped
[2024-03-02 00:08:43,247] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('accion', 'asignarSeries'), ('series', '1'), ('grupos', '1')])
[2024-03-02 00:13:14,930] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('accion', 'asignarSeries'), ('series', '1'), ('grupos', '1')])
[2024-03-02 00:13:31,857] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('accion', 'asignarSeries'), ('series', '1'), ('grupos', '1')])
[2024-03-02 00:13:54,344] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('series', '1'), ('grupos', '1')])
[2024-03-02 00:15:35,434] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('series', '1'), ('grupos', '1')])
[2024-03-02 00:15:55,383] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('series', '7'), ('grupos', '1')])
[2024-03-02 00:44:09,283] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('series', '1'), ('grupos', '1')])
[2024-03-02 00:49:30,162] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('series', '1'), ('grupos', '1'), ('submit_action', 'asignarSerie')])
[2024-03-02 00:51:25,666] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('1', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2024-03-02 00:51:37,486] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('7', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2024-03-02 01:16:15,290] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('1', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2024-03-02 01:16:18,376] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('7', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2024-03-02 13:35:26,279] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('nuevo_nombre', '213123123')])
[2024-03-02 13:35:45,247] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('nuevo_nombre', '1211111111')])
[2024-03-02 13:38:02,144] [ERROR] [main] Acción no reconocida: ImmutableMultiDict([('nuevo_nombre', '123123')])
[2024-03-02 16:16:15,088] [ERROR] [main] Ocurrió un error al agregar el ejercicio: (sqlite3.IntegrityError) UNIQUE constraint failed: serie_asignada.id_serie, serie_asignada.id_grupo
[SQL: INSERT INTO serie_asignada (id_serie, id_grupo) VALUES (?, ?)]
[parameters: ('7', '1')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2024-03-05 00:41:58,541] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: agregarCarpetaSerieEstudiante() takes 2 positional arguments but 3 were given
[2024-03-05 13:59:53,256] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: agregarCarpetaSerieEstudiante() takes 2 positional arguments but 3 were given
[2024-03-05 13:59:59,931] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: agregarCarpetaSerieEstudiante() takes 2 positional arguments but 3 were given
[2024-03-05 14:00:05,467] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: agregarCarpetaSerieEstudiante() takes 2 positional arguments but 3 were given
[2024-03-05 14:00:14,894] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: agregarCarpetaSerieEstudiante() takes 2 positional arguments but 3 were given
[2024-03-05 16:32:19,769] [ERROR] [main] Ocurrió un error al agregar la carpeta de la serie: agregarCarpetaSerieEstudiante() takes 2 positional arguments but 3 were given
[2024-03-06 22:17:24,581] [ERROR] [main] Ocurrió un error al guardar los archivos .java: [Errno 2] No such file or directory: 'ejerciciosPropuestos/Serie_1/Ejercicio_1/src/test/java/org/example/Parte3Test.java'
